#!/usr/bin/env python3
"""Generate port/hd_entity_table.inc: entity model texture/palette buffer -> HD asset path.

Entity models (src/entity/model/<Name>[_gfx].c) name their textures D_0A<offset>_<rom>, where offset
is the position inside the entity's 0x0A segment; the pack files them as entities/<Name>/tex_<offset>
and palette variants as tex_<offset>@tlut_<offset>. Only buffers port/ui_texture_loader.c fills are kept.

usage: gen_hd_entity_table.py [pack.o2r]
"""
import os
import re
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOADER = os.path.join(ROOT, "port", "ui_texture_loader.c")
MODELS = os.path.join(ROOT, "src", "entity", "model")
OUT = os.path.join(ROOT, "port", "hd_entity_table.inc")
PACK = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "texture", "paperboat-hd.o2r")

pack_images = {n[len("alt/"):].split("@")[0] for n in zipfile.ZipFile(PACK).namelist() if n.startswith("alt/")}
pack_dirs = {os.path.dirname(p) for p in pack_images}
loader_syms = set(re.findall(r"^extern u8 (\w+)\[\];", open(LOADER).read(), re.M))
include_re = re.compile(r'INCLUDE_(IMG|PAL)\("[^"]+",\s*(D_0A([0-9A-F]{6})_\w+)\)')
inline_re = re.compile(r"^unsigned char (D_0A([0-9A-F]{6})_\w+)\[\]", re.M)

images, palettes = {}, {}
for name in sorted(os.listdir(MODELS)):
    if not name.endswith(".c"):
        continue
    entity = re.sub(r"_(gfx|anim)$", "", name[:-2])
    with open(os.path.join(MODELS, name), errors="replace") as f:
        src = f.read()
    # Some models still carry their data inline instead of through INCLUDE_IMG/PAL.
    found = [(k, s, o) for k, s, o in include_re.findall(src) if s in loader_syms]
    found += [("", s, o) for s, o in inline_re.findall(src)]
    for kind, sym, off in found:
        off = "%X" % int(off, 16)
        if kind != "PAL" and f"entities/{entity}/tex_{off}" in pack_images:
            images[sym] = f"entities/{entity}/tex_{off}"
        elif kind != "IMG" and f"entities/{entity}" in pack_dirs:
            palettes[sym] = f"entities/{entity}/tlut_{off}"

lines = ["// Generated by tools/gen_hd_entity_table.py; do not edit.", 'extern "C" {']
lines += [f"extern unsigned char {s}[];" for s in sorted(images) + sorted(palettes)]
lines += ["}", "", "const HdNamedAsset kEntityImages[] = {"]
lines += [f'    {{ {s}, "{images[s]}" }},' for s in sorted(images)]
lines += ["};", "", "const HdNamedAsset kEntityPalettes[] = {"]
lines += [f'    {{ {s}, "{palettes[s]}" }},' for s in sorted(palettes)]
lines += ["};", ""]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"{len(images)} images, {len(palettes)} palettes -> {os.path.relpath(OUT, ROOT)}")
