#!/usr/bin/env python3
"""Generate port/hd_icon_table.inc: icon-segment offset -> HD asset path, from include/icon_offsets.h."""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "include", "icon_offsets.h")
OUT = os.path.join(ROOT, "port", "hd_icon_table.inc")

define_re = re.compile(r"#define ICON_([a-z]+)_(\w+?)(_disabled)?_(raster|palette) (0x[0-9A-Fa-f]+)")

rasters = {}  # offset -> path; the first non-disabled name owns a shared raster
palettes = {}  # offset -> (path, disabled)
for dirname, name, disabled, kind, off in define_re.findall(open(SRC).read()):
    off = int(off, 16)
    path = f"icons/{dirname}/{name}"
    if kind == "raster":
        if off not in rasters and not disabled:
            rasters[off] = path
    else:
        palettes.setdefault(off, (path, bool(disabled)))

lines = ["// Generated by tools/gen_hd_icon_table.py; do not edit.", "const HdIconRaster kIconRasters[] = {"]
lines += [f'    {{ 0x{o:X}, "{p}" }},' for o, p in sorted(rasters.items())]
lines += ["};", "", "const HdIconPalette kIconPalettes[] = {"]
lines += [f'    {{ 0x{o:X}, "{p}", {"true" if d else "false"} }},' for o, (p, d) in sorted(palettes.items())]
lines += ["};", ""]

with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"{len(rasters)} rasters, {len(palettes)} palettes -> {os.path.relpath(OUT, ROOT)}")
