#!/usr/bin/env python3
"""Generate port/hd_ui_table.inc: address -> asset path for every ROM-loaded UI image/palette.

Joins the buffers filled by port/ui_texture_loader.c with the asset paths from the
INCLUDE_IMG/INCLUDE_PAL lines in src/. Rerun after adding buffers to the loader.
ui/ assets keep their path; others (pause/, level_up/, ...) are filed by the pack under a category
folder, so they're only kept when the pack has them.

usage: gen_hd_ui_table.py [pack.o2r]
"""
import os
import re
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOADER = os.path.join(ROOT, "port", "ui_texture_loader.c")
OUT = os.path.join(ROOT, "port", "hd_ui_table.inc")
PACK = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "texture", "paperboat-hd.o2r")
CATEGORIES = ["", "misc/", "battle/", "world/"]

pack_files = {n[len("alt/"):] for n in zipfile.ZipFile(PACK).namelist() if n.startswith("alt/")}
pack_images = {n.split("@")[0] for n in pack_files}
pack_dirs = {os.path.dirname(n) for n in pack_images}
loader_syms = set(re.findall(r"^extern u8 (\w+)\[\];", open(LOADER).read(), re.M))


def pack_path(kind, path):
    if path.startswith("ui/"):
        return path
    for cat in CATEGORIES:
        if (cat + path) in pack_images or (kind == "PAL" and os.path.dirname(cat + path) in pack_dirs):
            return cat + path
    return None


include_re = re.compile(r'INCLUDE_(IMG|PAL)\("([^"]+)\.(png|pal)",\s*(\w+)\)')
images, palettes = {}, {}
for dirpath, _, files in os.walk(os.path.join(ROOT, "src")):
    for name in files:
        if not name.endswith(".c"):
            continue
        with open(os.path.join(dirpath, name), errors="replace") as f:
            for kind, path, _, sym in include_re.findall(f.read()):
                mapped = pack_path(kind, path) if sym in loader_syms else None
                if mapped is not None:
                    (images if kind == "IMG" else palettes)[sym] = mapped

if not images:
    sys.exit("no UI images found")

lines = [
    "// Generated by tools/gen_hd_ui_table.py; do not edit.",
    'extern "C" {',
]
lines += [f"extern unsigned char {s}[];" for s in sorted(images) + sorted(palettes)]
lines += ["}", "", "const HdNamedAsset kUiImages[] = {"]
lines += [f'    {{ {s}, "{images[s]}" }},' for s in sorted(images)]
lines += ["};", "", "const HdNamedAsset kUiPalettes[] = {"]
lines += [f'    {{ {s}, "{palettes[s]}" }},' for s in sorted(palettes)]
lines += ["};", ""]

with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"{len(images)} images, {len(palettes)} palettes -> {os.path.relpath(OUT, ROOT)}")
